// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu919P6fXDr7YibmopJcEV4xKMh7l_GZ8',
    appId: '1:1029957735829:web:2c73c0485bcfdc7fab129c',
    messagingSenderId: '1029957735829',
    projectId: 'w4-catalog',
    authDomain: 'w4-catalog.firebaseapp.com',
    storageBucket: 'w4-catalog.firebasestorage.app',
    measurementId: 'G-X8VJMYNMBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1QICOJauHdO0Nk9icO_b5vezneeoybSc',
    appId: '1:1029957735829:android:91568779071d3c6eab129c',
    messagingSenderId: '1029957735829',
    projectId: 'w4-catalog',
    storageBucket: 'w4-catalog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ8nyeaJo2deYbMUJBtxMhYo5v1h9Zzx0',
    appId: '1:1029957735829:ios:0f1c15bb62f8ff83ab129c',
    messagingSenderId: '1029957735829',
    projectId: 'w4-catalog',
    storageBucket: 'w4-catalog.firebasestorage.app',
    iosBundleId: 'com.example.marketPlace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ8nyeaJo2deYbMUJBtxMhYo5v1h9Zzx0',
    appId: '1:1029957735829:ios:0f1c15bb62f8ff83ab129c',
    messagingSenderId: '1029957735829',
    projectId: 'w4-catalog',
    storageBucket: 'w4-catalog.firebasestorage.app',
    iosBundleId: 'com.example.marketPlace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu919P6fXDr7YibmopJcEV4xKMh7l_GZ8',
    appId: '1:1029957735829:web:210fa43c38d3a3f8ab129c',
    messagingSenderId: '1029957735829',
    projectId: 'w4-catalog',
    authDomain: 'w4-catalog.firebaseapp.com',
    storageBucket: 'w4-catalog.firebasestorage.app',
    measurementId: 'G-KMJHERFDZV',
  );
}
